shared:
    image: node:14

jobs:
  A:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
      - set-label: |
          meta set label 'Yahoo http://yahoo.com, and scrwedriver https://screwdriver.cd, <script>alert("XSS")</script> <img src="//yahoo.com/fakeAddressToTrackyourIP" />' # this will show up in your pipeline events page
  B:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  C:
    requires: [A]
    steps:
      - ok: echo ok
      - timeout: sleep 60;
